const router = require('express').Router()
const authRouter = require('./auth.route')
const adminRouter = require('./admin.route')
const teacherRouter = require('./teacher.route')
const studentRouter = require('./student.route')
const subjectRouter = require('./subject.route')
const questionBankRouter = require('./questionBank.route')
const questionRouter = require('./question.route')
const examinationRouter = require('./examination.route')
const examRouter = require('./exam.route')
const testRouter = require('./test.route')
const { verifyToken } = require('~/middlewares/auth.middleware')

router.use('/auth', authRouter)
router.use('/admins', verifyToken, adminRouter)
router.use('/teachers', verifyToken, teacherRouter)
router.use('/students', verifyToken, studentRouter)
router.use('/subjects', verifyToken, subjectRouter)
router.use('/question-banks', verifyToken, questionBankRouter)
router.use('/questions', verifyToken, questionRouter)
router.use('/examinations', verifyToken, examinationRouter)
router.use('/exams', verifyToken, examRouter)
router.use('/tests', testRouter)

module.exports = router
